export const LOAD_NEXT_CHAPTER          = 'LOAD_NEXT_CHAPTER';
export const LOAD_PREVIOUS_CHAPTER      = 'LOAD_PREVIOUS_CHAPTER';

export const CLEAR_COMIC_IMAGES         = 'CLEAR_COMIC_IMAGES';
export const SWITCH_CHAPTER_REQUEST     = 'SWITCH_CHAPTER_REQUEST';
export const SWITCH_CHAPTER             = 'SWITCH_CHAPTER';
export const SWITCH_TO_NEXT_CHAPTER     = 'SWITCH_TO_NEXT_CHAPTER';
export const SWITCH_TO_PREVIOUS_CHAPTER = 'SWITCH_TO_PREVIOUS_CHAPTER';

export const NAVIGATE                   = 'NAVIGATE';

export const INIT_COMIC_MANAGER         = 'INIT_COMIC_MANAGER';
export const SET_COMIC_NAME             = 'SET_COMIC_NAME';

/* Search Related Action Types */
export const SHOW_LOAD_INDICATOR        = 'SHOW_LOAD_INDICATOR';
export const HIDE_LOAD_INDICATOR        = 'HIDE_LOAD_INDICATOR';
export const SEARCH_COMIC_REQUEST       = 'SEARCH_COMIC_REQUEST';
export const APPEND_SEARCH_RESULTS      = 'APPEND_SEARCH_RESULTS';
export const REPLACE_SEARCH_RESULTS     = 'REPLACE_SEARCH_RESULTS';
export const CLEAR_SEARCH_RESULT        = 'CLEAR_SEARCH_RESULT';
export const UPDATE_SEARCH_KEYWORD      = 'UPDATE_SEARCH_KEYWORD';

/* UI actions */
export const TOGGLE_APP_DRAWER          = 'TOGGLE_APP_DRAWER';
export const CHANGE_DRAWER_STATE        = 'CHANGE_DRAWER_STATE';
export const INCREASE_ZOOM_RATE         = 'INCREASE_ZOOM_RATE';
export const DECREASE_ZOOM_RATE         = 'DECREASE_ZOOM_RATE';
export const RESET_ZOOM_RATE            = 'RESET_ZOOM_RATE';
export const TOGGLE_TOOLBAR             = 'TOGGLE_TOOLBAR';
export const RESET_TOOLBAR_POSITION     = 'RESET_TOOLBAR_POSITION';

/* Collections */
export const FETCH_ALL_COLLECTION       = 'FETCH_ALL_COLLECTION';
export const FETCH_RECENT_COMICS        = 'FETCH_RECENT_COMICS';
export const FETCH_READING_RECORD       = 'FETCH_READING_RECORD';
export const FETCH_CHAPTER_CACHE        = 'FETCH_CHAPTER_CACHE';
