export const LOAD_NEXT_CHAPTER = 'LOAD_NEXT_CHAPTER';
export const LOAD_PREVIOUS_CHAPTER = 'LOAD_PREVIOUS_CHAPTER';

export const CLEAR_COMIC_IMAGES = 'CLEAR_COMIC_IMAGES';
export const SWITCH_CHAPTER_REQUEST = 'SWITCH_CHAPTER_REQUEST';
export const SWITCH_CHAPTER = 'SWITCH_CHAPTER';
export const SWITCH_TO_NEXT_CHAPTER = 'SWITCH_TO_NEXT_CHAPTER';
export const SWITCH_TO_PREVIOUS_CHAPTER = 'SWITCH_TO_PREVIOUS_CHAPTER';

export const NAVIGATE = 'NAVIGATE';

export const INIT_COMIC_MANAGER = 'INIT_COMIC_MANAGER';
export const SET_COMIC_NAME = 'SET_COMIC_NAME';

/* Search Related Action Types */
export const SHOW_LOAD_INDICATOR = 'SHOW_LOAD_INDICATOR';
export const SEARCH_COMIC_REQUEST = 'SEARCH_COMIC_REQUEST';
export const APPEND_SEARCH_RESULTS = 'APPEND_SEARCH_RESULTS';
export const REPLACE_SEARCH_RESULTS = 'REPLACE_SEARCH_RESULTS';
