title: Comics Reader
description: "一個中文漫畫閱讀器"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yukaii.tw/ComicsReader" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

google_analytics_id: UA-49526118-9
